[phases.setup]
nixPkgs = ["...", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd client && npm ci --include=dev --prefer-offline --no-audit && cd ../server && npm ci --include=dev --prefer-offline --no-audit"]

[phases.build]
cmds = ["...", "chmod +x ./build-railway.sh", "bash ./build-railway.sh"]

[start]
cmd = "node server/dist/index.js"

[variables]
NODE_ENV = "production"
