[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd client && npm ci --prefer-offline --no-audit && cd ../server && npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["cd client && npm run build && cd ../server && npm run build && echo '--- DEBUG LS client ---' && ls -la ../client && echo '--- DEBUG LS client/.next ---' && ls -la ../client/.next && cp -r ../client/.next . && (test -d ../client/public && cp -r ../client/public . || true) && echo '--- DEBUG LS server ---' && ls -la ."]

[start]
cmd = "cd server && npm start"

[variables]
NODE_ENV = "production"
